# Recursos adicionales {#sec-add-resources}

## Recursos para Ciencias Agrícolas y Medioambientales

- [R Packages for Agricultural Research](https://agstats.io/post/keeping-up-with-r/) (J. Piaskowski, Univ. of Idaho, 2024).

- [Data Analysis and Visualization in R for Ecologist](https://datacarpentry.org/R-ecology-lesson/) (Data Carpentry).

- [Statistical Analysis of Agricultural Experiments using R](https://rstats4ag.org/) (A. Kniss y J. Streibig, 2019).

## Recursos de aprendizaje generales

- [Finding Your Way to R](https://education.rstudio.com/learn/): Tutorial creado por el equipo educativo de Posit.
- [Learn the tidyverse](https://www.tidyverse.org/learn/): Recursos para profundizar en el análisis de datos con R y
los paquetes del Tidyverse.
- [Statistical Inference via Data Science](https://moderndive.com/) (C. Ismay y  A.Y. Kim, 2024): Un libro estupendo
para repasar conceptos estadísticos con una aproximación práctica, utilizando R y los paquetes del Tidyverse.


### Ejercicios y referencias sobre `tidyverse`

Llegados a este punto, lo más importante es realizar la mayor cantidad posible
de ejercicios y ejemplos para afianzar nuestro conocimiento de las funciones de los paquetes
`dplyr` y `tidyr`. Sobre todo si tenemos todavía poca experiencia en
programación (y aunque sí la tengamos, *también*), es importante tener **mucha
paciencia** tanto con el propio lenguaje como con nosotros mismos.

`dplyr` define una serie de operaciones para manipulación y consulta de datos que
no son arbitrarias. Llevan definidas desde hace décadas, cuando expertos en bases
de datos pensaron en la forma de organizar la información de manera más eficiente
y cómo recuperarla y modificarla posteriormente.

Por tanto, es importante no desesperarse y poco a poco ir habituándose a las
funciones existentes y a **construir consultas** con estas piezas básicas.

Recomendamos a continuación varias fuentes en las que se pueden encontrar muchos
ejemplos adicionales y ejercicios para practicar:

1. La versión online del libro *R for Data Science* de H. Wikcham [@Wickham2017]
incluye en el [capítulo 5](https://r4ds.had.co.nz/transform.html) más ejemplos
de estas mismas operaciones, utilizando datos del paquete `nycflights13`.
2. Los materiales en línea del curso `Stat545` (<https://stat545.com/>), 
creado por J. Bryan contienen varios capítulos relevantes para repasar
y practicar. Varios de estos capítulos también proponen ejercicios
adicionales para resolver:

  * El [capítulo 6](https://stat545.com/dplyr-intro.html) es una introducción a las
  operaciones básicas con `dplyr`.
  * El [capítulo 7](https://stat545.com/dplyr-single.html) amplía con más 
  ejemplos la explicación de las funciones que solo involucran a una tabla.
  * El [capítulo 14](https://stat545.com/multiple-tibbles.html) se muestra como
  ampliar una tabla añadiendo más filas o más columnas procedentes de otras
  tablas.
  * El [capítulo 15](https://stat545.com/join-cheatsheet.html) amplía 
  las operaciones *join*, explicando gráficamente y de forma clara cómo
  se combinan las tablas con cada operación y el resultado final.

3. El [capítulo 3](https://moderndive.com/3-wrangling.html) del 
libro *Modern Dive into R* de C. Ismay y A.Y. Kim, contiene más ejemplos y
explicaciones gráficas para entender todas estas operaciones.



## Creación de gráficos en R 

- [The R Graph Gallery](https://r-graph-gallery.com/): Ofrece cientos de ejemplos de construcción
de gráficos en R, algunos muy sofisticados.

- Libro [Data Visualization: A practical introduction](https://socviz.co/) (K. Healy, Duke Univ., 2018): Aunque el código
puede haber quedado algo desfasado por la evolución de los paquetes software en R, sigue siendo la fuente
de referencia principal sobre creación de gráficos (en general) para visualización de datos.

## Modelos estadísticos y aprendizaje automático

### Tidymodels

- [Tidymodels](https://www.tidymodels.org/): Se trata de un *framework* para trabajar con
modelos estadísticos siguiendo los principios de trabajo y organización del Tidyverse.
Los principales paquetes se encuentran reunidos en un solo metapaquete denominado `tidymodels`,
que podemos instalar directamente para probar toda la suite de herramientas que incluye:

```{r}
#| label: install-tidymodels
#| eval: false

install.packages("tidymodels")
```

- [Getting started with Tidymodels](https://www.tidymodels.org/start/).
- [Learn Tidymodels](https://www.tidymodels.org/learn/): Colección de tutoriales sobre ajuste de
modelos con Tidymodels.

### `mlr3`

El paquete `mlr3` [@mlr3] es una alternativa menos conocida pero muy potente para
implementar modelos de aprendizaje automático en R.

- [`mlr3` website](https://mlr3.mlr-org.com/)

Esta versión ha sido rediseñada para favorecer la claridad del código y su modularidad,
separando otras funciones no principales en muchos paquetes complementarios que también
forman un ecosistema alrededor de `mlr3`.

## Bioconductor

La lista de recursos adicionales no quedaría completa sin mencionar el que, quizá, es uno
de los proyectos más importantes dentro del universo R: Bioconductor [@bioconductor]. Se trata de
un enorme ecosistema de paquetes (más de 3.000) que incluyen numerosas herramientas para
Bioinformática, datos experimentales y automatización de flujos de trabajo.

- [About Bioconductor](https://www.bioconductor.org/about/).