# Introducción {.unnumbered}

Bienvenidos al Taller de Introducción a R para estudiantes del Programa
de Doctorado en Ciencias Agrarias y Ambientales de la UCLM.

En este taller se introducen los elementos básicos para programar con el
lenguaje R. Este es un lenguaje de programación científica, creado originalmente
para aplicaciones matemáticas y estadísticas y que está disponible como
software libre, bajo licencia GNU GPL 3.

Por otra parte, este no es un taller de introducción a la programación. Si
no estás familiarizado con conceptos básicos como variables, sentencias o comandos,
control de flujo de ejecución, funciones, etc. podrás seguir los contenidos desde
un punto de vista práctico, pero muy probablemente no comprendas del todo
bien cómo funcionan los ejemplos que se muestran. En este caso, te recomendamos
que te familiarices primero con los conceptos básicos de programación antes
repasar estos contenidos. Puedes consultar el capítulo @sec-add-resources para
encontrar referencias que te ayuden a aprender conceptos básicos de programación.

Este es un **taller práctico**, que presenta numerosos ejemplos de comandos y código
ejecutable para aprender a programar con el lenguaje R. Nuestro objetivo no es
realizar una presentación exhaustiva de todas las posibilidades que ofrece R, sino
solo los elementos básicos para adquirir destreza a nivel elemental. A partir de
aquí, deberías ser capaz de seguir aprendiendo sobre aspectos del lenguaje R y las
opciones que ofrecen multitud de paquetes de expansión de funcionalidad publicados en
el repositorio CRAN (consulta la sección @sec-r-packages).

Este manual que acompaña al Taller de Introducción a R ha sido elaborado con Quarto
(<https://quarto.org>), una herramienta de creación de documentación científica compatible,
entre otros lenguajes, con R. Para aprender más detalles sobre Quarto puedes visitar
la completa guía disponible en <https://quarto.org/docs/guide/>. En concreto, la creación
de libros como este utilizando Quarto está documentada en <https://quarto.org/docs/books>.

## Licencia

A menos que explícitamente se indque lo contrario, los materiales proporcionados en este
taller se publican bajo una licencia Creative Commons Atribución-Compartir-Igual (CC-BY-SA)
versión 4.0. Se puede acceder a los términos legales y el texto completo de esta licencia
mediante [este enlace](https://creativecommons.org/licenses/by-sa/4.0/deed.es).